### ISSUE TITLE
Connection Refused is not being handled properly.

### ISSUE THREAD

**Issue by drapergeek** [drapergeek/wuzup#21]
2012-11-25T23:51:58+00:00 app[web.1]: Errno::ECONNREFUSED (Connection refused - connect(2)):
2012-11-25T23:51:58+00:00 app[web.1]:   app/models/service_checker.rb:19:in `site_status'
2012-11-25T23:51:58+00:00 app[web.1]:   app/models/service_checker.rb:24:in`check_site_status'
2012-11-25T23:51:58+00:00 app[web.1]:   app/controllers/admin/manual_site_checks_controller.rb:5:in `block (2 levels) in show'
2012-11-25T23:51:58+00:00 app[web.1]:   app/models/service_checker.rb:9:in`execute'
2012-11-25T23:51:58+00:00 app[web.1]:   app/models/service_checker.rb:15:in `create_service_check'
2012-11-25T23:51:58+00:00 app[web.1]:   app/controllers/admin/manual_site_checks_controller.rb:4:in`times'
2012-11-25T23:51:58+00:00 app[web.1]: Completed 500 Internal Server Error in 1042ms
2012-11-25T23:51:58+00:00 app[web.1]: 
2012-11-25T23:51:58+00:00 app[web.1]:   app/controllers/admin/manual_site_checks_controller.rb:4:in `block in show'
2012-11-25T23:51:58+00:00 app[web.1]:   app/controllers/admin/manual_site_checks_controller.rb:3:in`each'
2012-11-25T23:51:58+00:00 app[web.1]: Processing by Admin::ManualSiteChecksController#show as HTML
2012-11-25T23:51:58+00:00 app[web.1]:   app/controllers/admin/manual_site_checks_controller.rb:3:in `show'

Maybe we should catch all exceptions?

**Comment by brentm5** [comment]
I know how to fix this.  Just dont know how to test it first.

**Comment by drapergeek** [comment]
LOL.  Spin up a sinatra server!

**Comment by drapergeek** [comment]
https://github.com/yammer/sched.do/blob/master/spec/support/fake_yammer.rb.  Here's a good example of using fakeweb which is what we'll need to start using for testing more extensively anyway.

**Comment by drapergeek** [comment]
Especially once we hit testing apis.
